global:
  imagePullPolicy: IfNotPresent

  nexusRegistry: "speshway-test-shared-alb-1055767501.ap-south-1.elb.amazonaws.com:8081/docker-hosted"

  ecrRegistry: "179897609830.dkr.ecr.ap-south-1.amazonaws.com"

services:

  auth:
    name: auth-service
    namespace: auth
    image: auth-service
    registry: nexus
    tag: qa-001
    port: 8081
    replicas: 1
    serviceType: ClusterIP

  gateway:
    name: gateway-service
    namespace: gateway
    image: gateway-service
    registry: nexus
    tag: qa-001
    port: 8080
    replicas: 1
    serviceType: ClusterIP

  user:
    name: user-service
    namespace: user
    image: user-service
    registry: nexus
    tag: qa-001
    port: 8082
    replicas: 1
    serviceType: ClusterIP

  admin:
    name: admin-service
    namespace: admin
    image: admin-service
    registry: nexus
    tag: qa-001
    port: 8082
    replicas: 1
    serviceType: ClusterIP

  employee:
    name: employee-service
    namespace: employee
    image: employee-service
    registry: nexus
    tag: qa-001
    port: 8083
    replicas: 1
    serviceType: ClusterIP

  customer:
    name: customer-service
    namespace: customer
    image: customer-service
    registry: nexus
    tag: qa-001
    port: 8084
    replicas: 1
    serviceType: ClusterIP

  hr:
    name: hr-service
    namespace: hr
    image: speshway-test-hr
    registry: ecr
    tag: qa-001
    port: 8085
    replicas: 1
    serviceType: ClusterIP

  task:
    name: task-service
    namespace: task
    image: speshway-test-task
    registry: ecr
    tag: qa-001
    port: 8089
    replicas: 1
    serviceType: ClusterIP

database:
  host: speshway-test-crm-test-rds.cxeuyga6q0qq.ap-south-1.rds.amazonaws.com
  port: 3306
  name: speshway
