pipeline {

    agent any
    
    parameters {
        booleanParam(
            name: 'INITIAL_BUILD',
            defaultValue: false,
            description: 'Build and push all microservice images for the initial deployment'
        )
    }

    tools {
        maven 'maven-3.9'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    stage('Detect Changes') {
    steps {
        script {

            def changedFiles = []

            currentBuild.changeSets.each { changeSet ->

                changeSet.items.each { entry ->

                    entry.affectedFiles.each { file ->

                        changedFiles.add(file.path)

                    }
                }
            }

            writeFile(
                file: 'changed-files.txt',
                text: changedFiles.unique().join('\n') + '\n'
            )

            echo "Changed files:"
            echo changedFiles.unique().join('\n')
        }

        sh './jenkins/ci/detect-changes.sh'

        script {
            def changes =
                readProperties file: 'changed-services.properties'

            env.CHANGED_SERVICES =
                changes.CHANGED_SERVICES

            echo "Changed Services: ${env.CHANGED_SERVICES}"
       		 }
 	   }
	}

    stage('Build') {
            steps {
                sh './jenkins/ci/build.sh'
            }
        }

    stage('Test') {
            steps {
                sh './jenkins/ci/test.sh'
            }
        }
    
    stage('Docker Build') {
 	   steps {
        	sh './jenkins/ci/docker-build.sh'
              }
	  }
    stage('Trivy Image Scan') {
            steps {
                sh './jenkins/ci/trivy-scan.sh'
            }
        }

        stage('Push Images') {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'nexus-docker',
                        usernameVariable: 'NEXUS_USERNAME',
                        passwordVariable: 'NEXUS_PASSWORD'
                    )
                ]) {

                        sh './jenkins/ci/push-images.sh'
                    }
                }
            }
    stage('EKS Authentication') {
    	steps {
        	sh './jenkins/cd/eks-auth.sh'
    	}
	}

    stage('Helm Deploy') {
    	steps {
 	     withCredentials([
            usernamePassword(
                credentialsId: 'nexus-docker',
                usernameVariable: 'NEXUS_USERNAME',
                passwordVariable: 'NEXUS_PASSWORD'
               )
             ]){
        	sh './jenkins/cd/helm-deploy.sh'
    	  }
	 }
	}
    stage('Rollout Status') {
    	steps {
        	sh './jenkins/cd/rollout-status.sh'
    	}
	}

    stage('Smoke Test') {
    	steps {
        	sh './jenkins/cd/smoke-test.sh'
    	}
	}
    }
    
  
  post {

        success {
            echo 'Checkout, Build, Test, SonarQube Analysis and Quality Gate completed successfully.'
        }

        failure {
            echo 'Pipeline failed. Check the failed stage and console output.'
        }

    }
}
